### ISSUE TITLE
可以和Bootstrap的css文件那个兼容使用吗

### ISSUE THREAD

**Issue by MikiraSora** [metakirby5/yorha#8]
通过link顺序勉强能看
但如果使用dropdown之类的玩意就不行了
不知道有没有办法或者是其他能帮助我，毕竟我对这方面比较新人:X

顺便说一句，牛逼:D

**Comment by metakirby5** [comment]
Sorry, I can't read Chinese :( However, Google Translate tells me there's an issue with the dropdown menu, which is true on Chrome. I've just fixed the dropdown menu background color in cb2f9fa, but please let me know if there are further issues. Thanks!

**Comment by MikiraSora** [comment]
I am so sorry I think wrong because of Location is chinese in your profile. My English is not well but I try 😄 
<br>
In fact I'm really like your CSS and **try to use your css file and Bootstrap** to my websites .
<br>
But there are **a lot of error about css element properties are covered by booststrapCSS** and I'm just a newbie of WebDesign/FrontEnd and so on. **I dont know how to solve it easy and right** , so I made **a new css file named [yorha_patch](http://mikirasora.moe/css/yorha_patch.css) for fixing these problem**.

You can visit my website and take a look
http://mikirasora.moe/
**Account:guest Pw:123456**
http://mikirasora.moe/account/loginin 
http://mikirasora.moe/api

your repo is **cool** , thank you 😄

**Comment by metakirby5** [comment]
Ah, I see. I would advise against combining CSS frameworks, since it's not easy to resolve conflicts between them. Instead, I suggest you use [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout) or [grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) styles to define your layout, and let visual styles be driven by yorha and any additional custom styles. Thanks for using this project :)

**Comment by metakirby5** [comment]
@MikiraSora I gave a shot at rewriting the HTML and CSS for your page: https://s.kirbi.es/mikirasora/

The only particularly difficult bit was getting the dropdown menu to work well, but everything else was fairly straightforward. Now you don't need any Bootstrap or Javascript!

**Comment by MikiraSora** [comment]
Yea,I will study and try ,thanks a lot
